# Generated by Django 3.1.3 on 2020-11-29 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('num_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=30)),
                ('prenom_client', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('telephone__gte', 100000000), ('telephone__lt', 1000000000)), name='tel_digits'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(date_de_naissance__lte=datetime.date(2002, 11, 30)), name='age18ans'),
        ),
    ]
