# Generated by Django 3.1.4 on 2020-12-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientsport',
            unique_together={('nom_sport', 'num_client')},
        ),
    ]
