# Generated by Django 3.1.3 on 2020-11-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_auto_20201130_1854'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('num_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('acompte', models.IntegerField()),
                ('date_reservation', models.DateField()),
                ('debut_sejour', models.DateField()),
                ('fin_sejour', models.DateField()),
                ('num_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camping.client')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
    ]
