# Generated by Django 3.1.4 on 2020-12-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_auto_20201210_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsport',
            name='nom_sport',
            field=models.ForeignKey(db_column='nom_sport', on_delete=django.db.models.deletion.CASCADE, to='camping.sport'),
        ),
        migrations.AlterField(
            model_name='clientsport',
            name='num_client',
            field=models.ForeignKey(db_column='num_client', on_delete=django.db.models.deletion.CASCADE, to='camping.client'),
        ),
    ]
