# Generated by Django 3.1.4 on 2020-12-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_auto_20201210_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcafebar',
            name='num_client',
            field=models.ForeignKey(db_column='num_client', on_delete=django.db.models.deletion.CASCADE, to='camping.client'),
        ),
        migrations.AlterField(
            model_name='clientcafebar',
            name='ref_conso',
            field=models.ForeignKey(db_column='ref_conso', on_delete=django.db.models.deletion.CASCADE, to='camping.cafebar'),
        ),
        migrations.AlterField(
            model_name='clientkaraoke',
            name='num_client',
            field=models.ForeignKey(db_column='num_client', on_delete=django.db.models.deletion.CASCADE, to='camping.client'),
        ),
        migrations.AlterField(
            model_name='clientkaraoke',
            name='ref_salle',
            field=models.ForeignKey(db_column='ref_salle', on_delete=django.db.models.deletion.CASCADE, to='camping.karaoke'),
        ),
        migrations.AlterField(
            model_name='clientproduitsuperette',
            name='num_client',
            field=models.ForeignKey(db_column='num_client', on_delete=django.db.models.deletion.CASCADE, to='camping.client'),
        ),
        migrations.AlterField(
            model_name='clientproduitsuperette',
            name='ref_produit',
            field=models.ForeignKey(db_column='ref_produit', on_delete=django.db.models.deletion.CASCADE, to='camping.produitsuperette'),
        ),
        migrations.AlterField(
            model_name='clientsalledesjeux',
            name='num_client',
            field=models.ForeignKey(db_column='num_client', on_delete=django.db.models.deletion.CASCADE, to='camping.client'),
        ),
        migrations.AlterField(
            model_name='clientsalledesjeux',
            name='ref_jeu',
            field=models.ForeignKey(db_column='ref_jeu', on_delete=django.db.models.deletion.CASCADE, to='camping.salledesjeux'),
        ),
        migrations.AlterField(
            model_name='sportintervenant',
            name='id_intervenant',
            field=models.ForeignKey(db_column='id_intervenant', on_delete=django.db.models.deletion.CASCADE, to='camping.intervenant'),
        ),
        migrations.AlterField(
            model_name='sportintervenant',
            name='nom_sport',
            field=models.ForeignKey(db_column='nom_sport', on_delete=django.db.models.deletion.CASCADE, to='camping.sport'),
        ),
        migrations.AlterField(
            model_name='sportmateriel',
            name='nom_materiel',
            field=models.ForeignKey(db_column='nom_materiel', on_delete=django.db.models.deletion.CASCADE, to='camping.materiel'),
        ),
        migrations.AlterField(
            model_name='sportmateriel',
            name='nom_sport',
            field=models.ForeignKey(db_column='nom_sport', on_delete=django.db.models.deletion.CASCADE, to='camping.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='clientcafebar',
            unique_together={('num_client', 'ref_conso')},
        ),
        migrations.AlterUniqueTogether(
            name='clientkaraoke',
            unique_together={('num_client', 'ref_salle')},
        ),
        migrations.AlterUniqueTogether(
            name='clientproduitsuperette',
            unique_together={('num_client', 'ref_produit')},
        ),
        migrations.AlterUniqueTogether(
            name='clientsalledesjeux',
            unique_together={('num_client', 'ref_jeu')},
        ),
        migrations.AlterUniqueTogether(
            name='sportintervenant',
            unique_together={('nom_sport', 'id_intervenant')},
        ),
        migrations.AlterUniqueTogether(
            name='sportmateriel',
            unique_together={('nom_materiel', 'nom_sport')},
        ),
    ]
