# Generated by Django 3.1.4 on 2020-12-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0004_auto_20201210_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsaison',
            name='code_saison',
            field=models.ForeignKey(db_column='code_saison', on_delete=django.db.models.deletion.CASCADE, to='camping.saison'),
        ),
        migrations.AlterField(
            model_name='reservationsaison',
            name='num_reservation',
            field=models.ForeignKey(db_column='num_reservation', on_delete=django.db.models.deletion.CASCADE, to='camping.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationservices',
            name='num_reservation',
            field=models.ForeignKey(db_column='num_reservation', on_delete=django.db.models.deletion.CASCADE, to='camping.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationservices',
            name='services_proposes',
            field=models.ForeignKey(db_column='services_proposes', on_delete=django.db.models.deletion.CASCADE, to='camping.servicesproposes'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationsaison',
            unique_together={('code_saison', 'num_reservation')},
        ),
        migrations.AlterUniqueTogether(
            name='reservationservices',
            unique_together={('num_reservation', 'services_proposes')},
        ),
    ]
