# Generated by Django 3.1.4 on 2020-12-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_auto_20201210_2055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profil',
            table='profil',
        ),
    ]
