# Generated by Django 3.1.3 on 2020-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_auto_20201202_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEmplacement',
            fields=[
                ('type_empl', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nb_pers_max', models.IntegerField()),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'type_emplacement',
            },
        ),
    ]
