# Generated by Django 3.1.3 on 2020-12-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_typeemplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('num_empl', models.IntegerField(primary_key=True, serialize=False)),
                ('type_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camping.typeemplacement')),
            ],
            options={
                'db_table': 'emplacement',
            },
        ),
    ]
